export const topics = {
    Music: 'images/music.avif',
    Sports: 'images/sports.avif',
    Technology: 'images/technology.avif',
    Art: 'images/art.avif',
    Science: 'images/science.avif',
    Wellness: 'images/wellness.avif',
    Education: 'images/education.avif',
    Business: 'images/business.avif',
    'Food And Drink': 'images/food-drink.avif',
    Travel: 'images/travel.avif',
    Gaming: 'images/gaming.avif',
    Movies: 'images/movies-entertainment.avif',
    Fashion: 'images/fashion.avif',
    Literature: 'images/literature.avif',
    Environment: 'images/environment.avif',
    Photography: 'images/photography.avif',
    'Social Impact': 'images/social-impact.avif',
    History: 'images/history-culture.avif',
    Spirituality: 'images/spirituality-religion.avif',
    Fitness: 'images/fitness.avif',
  }  