export const topics = {
    music: '/images/music-banner.jpg',
    sports: '/images/sports-banner.jpg',
    technology: '/images/technology-banner.jpg',
    art: '/images/art-banner.jpg',
    science: '/images/science-banner.jpg',
    healthAndWellness: '/images/health-wellness-banner.jpg',
    education: '/images/education-banner.jpg',
    businessNetworking: '/images/business-networking-banner.jpg',
    foodAndDrink: '/images/food-drink-banner.jpg',
    travelAdventure: '/images/travel-adventure-banner.jpg',
    gaming: '/images/gaming-banner.jpg',
    moviesEntertainment: '/images/movies-entertainment-banner.jpg',
    fashion: '/images/fashion-banner.jpg',
    literatureBooks: '/images/literature-books-banner.jpg',
    environmentSustainability: '/images/environment-sustainability-banner.jpg',
    photography: '/images/photography-banner.jpg',
    socialImpactVolunteering: '/images/social-impact-volunteering-banner.jpg',
    historyCulture: '/images/history-culture-banner.jpg',
    spiritualityReligion: '/images/spirituality-religion-banner.jpg',
    fitnessExercise: '/images/fitness-exercise-banner.jpg',
  }  